### PR TITLE
remove Husky checks in favor of PR-level checks

### PR DESCRIPTION
**Pull request by wmhilton**

### CODE REVIEW

**Comment by wmhilton** [comment]
ur freaking kidding me there's a snapshot test

**Comment by XVincentX** [comment]
I'm fine with the changes, but I think more people on the team should be involved in this decision and — more importantly — somebody claiming to take responsibility to set up the remaining infrastructure part (such as PR level checks)

**Comment by wmhilton** [comment]
@marbemac git commit for `studio` is now taking 22 seconds on my desktop because of all these checks

**Comment by wmhilton** [comment]
Capture11

**Comment by wmhilton** [comment]
here's the same thing on my mac



Not near as slow. But still, have to wait 4 seconds to be rejected  because of the commit message validation.

**Comment by XVincentX** [comment]
@wmhilton Maybe we can get away with it by reverting the order — commit lint first and then prettier?

**Pull request closed without merging**
