### PR TITLE
fix: buildCommand behavior in a monorepo

### PR DESCRIPTION
**Pull request by marcelltoth**
Assuming a fixed `node_modules` path breaks within a monorepo powered by yarn workspaces.

image

(because the dep is hoisted up to `.../source/stoplight/elements/node_modules/.bin/`)

There is no point in doing the resolution ourselves anyway. We can allow the shell to do the resolution based on PATH, which will then work regardless of where the dependency is located exactly.

### CODE REVIEW

**Comment by marcelltoth** [comment]
> 
> 
> Too risky. That would allow commands installed globally to work too, which would result in people forgetting to add a dependency because it would work on their machine. (Plus, it's always a terrible idea to rely on `$PATH` in my opinion.)
> 
> Let's do some kind of upword directory search starting at cwd for `node_modules/.bin/${baseCommand}`

What about `yarn run ${x}`?

Or this library: https://github.com/saltyshiomix/resolve-as-bin

`requre.resolve` acts weird for some reason.

image

**Comment by wmhilton** [comment]
> What about `yarn run ${x}`?

That only works on scripts in package.json, not actual binaries AFAICT.

> Or this library: https://github.com/saltyshiomix/resolve-as-bin

That library uses `spawn('npm bin')` to find the `.bin` directory, which won't work for monorepos either.

I bet I can find something...

**Comment by wmhilton** [comment]
https://github.com/sindresorhus/find-up looks good. I like sindresorhus's stuff.

**Comment by wmhilton** [comment]
@marcelltoth See if my commit works for your monorepo use case.

**Comment by marcelltoth** [comment]
> 
> 
> @marcelltoth See if my commit works for your monorepo use case.

Awesome! Works perfectly.

**Pull request merged**
