### PR TITLE
fix: monorepo bundle

### PR DESCRIPTION
**Pull request by mallachari**
Fixes: https://github.com/stoplightio/scripts/issues/89

Following https://github.com/stoplightio/scripts/pull/83 there's one more resolving to be done.

I've tested it with elements packages and they build solid esm. 
~Still would be good to wait for https://github.com/stoplightio/scripts/pull/90 before merging this one so we have it tested properly.~

### CODE REVIEW

**Review by marcelltoth — COMMENTED** [review]
Looks good to me! As you said, let's wait for #88 then merge master to gain confidence.

**Comment by mallachari** [comment]
Looks good
Screenshot 2021-07-16 at 10 36 55

**Review by marcelltoth — APPROVED** [review]
> Looks good
> Screenshot 2021-07-16 at 10 36 55

Now this is the confidence we should achieve everywhere! You just look at the tests, they all pass, so you're not worried about breaking stuff. See your work shine @mpodlasin 🚀 

Code still looks great, assuming you tested the bundle script in elements @mallachari, it's good to go.

**Comment by mallachari** [comment]
I briefly tested it with all elements repos and one example. It just requires changing tsconfig to use `esnext` instead of `commonjs`

**Pull request merged**
